apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-app
  labels:
    app: wisecow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
  containers:
    - name: wisecow-app
      image: atomar9968/wisecow-app:latest
      ports:
        - containerPort: 3000
      volumeMounts:
        - name: tls-secret
          mountPath: /etc/ssl/certs
          readOnly: true
  volumes:
    - name: tls-secret
      secret:
        secretName: wisecow-tls


