apiVersion: v1
kind: Service
metadata:
  name: wisecow-app
spec:
  type: NodePort
  selector:
    app: wisecow  # Change this to match the pod label
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
